### ISSUE TITLE
Screen reader accessibility for expandable components 

### ISSUE THREAD

**Issue by cliu02** [bloom-housing/ui-components#135]
This issue is from a DAHLIA accessibility audit. 

**Description**: On the [Listing Details page](https://dahlia-full.herokuapp.com/listings/a0W0P00000F8YG4UAN) for any DAHLIA listing, when screen reader users activate and expand these components they are redirected to the top, and the screen reader proceeds to read from the top of the screen. 

![screen reader bug](https://github.com/bloom-housing/ui-components/assets/32694266/902a3ccb-1ef2-46c7-a702-a5f045e1311c)

**How should this work?** When the accordion menu has been activated the screen reader should proceed to read the content within the expanded accordion.

**Comment by ColinBuyck** [comment]
From my first pass, I'm noticing that some of this issue is unique to DAHLIA's use of these components. In comparing bloom's listing page (testing with this [listing](https://bloom.exygy.dev/listing/f5f77fb6-4b17-4d5a-a1a8-430670423a61/testing_sfsdfdsfd_dsfdesf_ca)) and the linked Dahlia listing, only the DAHLIA mac voiceover output is landing at the top of the page. I'm also noticing the page refresh sound effect in DAHLIA so the entire page is reloading based on a state change affecting one small piece of the page. Potentially, there is some issue with where the component is being consumed or handled since the state change occurs within the component but without much familiarity of Dahlia's codebase... I'm unsure. My read is that this would be ideal for pairing and I'd estimate at a 2/3 since page refreshes have been tricky before and consuming the state change can be limiting @sarahlazarich.  

Not sure if I'm understanding the ideal behavior correctly, but if the wish is to read the second half only once expanded (not from the beginning), that would require UI-Component changes since the focus lands on the less button in Bloom's implementation and a user has to arrow-navigate back and read the text from the beginning. Definitely room for improvement there but might be worth separating out because the page reload issue seems much more critical.
